### ISSUE TITLE
语言问题？(Translation: Language Problem?)

### ISSUE THREAD

**Issue by UF4OVER** [HinsTech-GmbH/lib_ft6x36#1]
STM32的HAL库不支持C++吧？

Translation: Does the STM32 HAL library support C++?

**Comment by melektron** [comment]
The STM32Cube HAL itself is written in C but you can of course call it from C++.

With the PlatformIO build system you can just use C++ by creating .cpp files instead of .c files.

This library (lib_ft6x36) provides a C++ interface, so you cannot easily use it from C unless you manually provide mangled function declarations.
